export const bankInfo = [
  { id: "1", title: "Access Bank", code: "044" },
  { id: "2", title: "Citibank", code: "023" },
  { id: "3", title: "Diamond Bank", code: "063" },
  { id: "4", title: "Ecobank Nigeria", code: "050" },
  { id: "5", title: "Fidelity Bank Nigeria", code: "070" },
  { id: "6", title: "First Bank of Nigeria", code: "011" },
  { id: "7", title: "First City Monument Bank", code: "214" },
  { id: "8", title: "Guaranty Trust Bank", code: "058" },
  { id: "9", title: "Heritage Bank Plc", code: "030" },
  { id: "10", title: "Jaiz Bank", code: "301" },
  { id: "11", title: "Keystone Bank Limited", code: "082" },
  { id: "12", title: "Providus Bank Plc", code: "101" },
  { id: "13", title: "Polaris Bank", code: "076" },
  { id: "14", title: "Stanbic IBTC Bank Nigeria Limited", code: "221" },
  { id: "15", title: "Standard Chartered Bank", code: "068" },
  { id: "16", title: "Sterling Bank", code: "232" },
  { id: "17", title: "Suntrust Bank Nigeria Limited", code: "100" },
  { id: "18", title: "Union Bank of Nigeria", code: "032" },
  { id: "19", title: "United Bank for Africa", code: "033" },
  { id: "20", title: "Unity Bank Plc", code: "215" },
  { id: "21", title: "Wema Bank", code: "035" },
  { id: "22", title: "Zenith Bank", code: "057" },
];
